title: Mennato Allah Ahmed

description: AI & Quality Engineer | Computer Vision | Smart Manufacturing | Industrial IoT

show_downloads: false

theme: jekyll-theme-minimal

github:
is_project_page: false

author:
name: Mennato Allah Ahmed

social:
linkedin: "[www.linkedin.com/in/mennato-allah-ahmed-4b11002b4](http://www.linkedin.com/in/mennato-allah-ahmed-4b11002b4)"
email: "[mennatoallah.abdelsalam@gmail.com](mailto:mennatoallah.abdelsalam@gmail.com)"

markdown: kramdown

plugins:

* jekyll-seo-tag


