title: Mennato Allah Ahmed 
#logo: /assets/img/headshot_cirlce.png
#logo: /assets/img/headshot_circle.png
description: AI & Computer Vision | IoT | HCIA & Machine Learning Instructor
show_downloads: true
theme: jekyll-theme-minimal
