title: Mennato Allah Ahmed

logo: /assets/img/headshot_circle.png

description: AI & Quality Engineer | Computer Vision | Smart Manufacturing | Industrial IoT

show_downloads: true

theme: jekyll-theme-minimal

